/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaBiblioteca;

/**
 *
 * @author Usuario
 */
public class Interface extends javax.swing.JFrame {
    Gestionador gest= new Gestionador();
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        main_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        add_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        add_name = new javax.swing.JTextField();
        add_book = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        add_author = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        add_ed = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        add_year = new javax.swing.JTextField();
        message = new javax.swing.JLabel();
        add_cat = new javax.swing.JComboBox<>();
        search_panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        search_by_name = new javax.swing.JTextField();
        search_by_cat = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        search_table = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        search_by_author = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Inventario");
        main_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        add_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Agregar Libros");
        add_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        add_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_nameActionPerformed(evt);
            }
        });
        add_panel.add(add_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 160, -1));

        add_book.setText("Agregar Libro");
        add_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_bookActionPerformed(evt);
            }
        });
        add_panel.add(add_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        jLabel4.setText("Nombre del Libro");
        add_panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel5.setText("Categoria");
        add_panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel6.setText("Autor del Libro");
        add_panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        add_author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_authorActionPerformed(evt);
            }
        });
        add_panel.add(add_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 160, -1));

        jLabel7.setText("Editorial");
        add_panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 20));

        add_ed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_edActionPerformed(evt);
            }
        });
        add_panel.add(add_ed, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 160, -1));

        jLabel8.setText("Año de publicacion");
        add_panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        add_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_yearActionPerformed(evt);
            }
        });
        add_panel.add(add_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 160, -1));
        add_panel.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 170, 190));

        add_cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione una categoria--", "Generalidades", "Filosofía y Psicología", "Religión, Teología", "Ciencias Sociales", "Lenguas", "Ciencias Básicas", "Tecnología y Ciencias Aplicadas", "Artes y recreación", "Literatura", "Historia y Geografía" }));
        add_panel.add(add_cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 160, -1));

        jTabbedPane1.addTab("Agregar", add_panel);

        search_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Busqueda de libros");
        search_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));
        search_panel.add(search_by_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 130, -1));

        search_by_cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione una categoria--", "Generalidades", "Filosofía y Psicología", "Religión, Teología", "Ciencias Sociales", "Lenguas", "Ciencias Básicas", "Tecnología y Ciencias Aplicadas", "Artes y recreación", "Literatura", "Historia y Geografía" }));
        search_by_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_by_catActionPerformed(evt);
            }
        });
        search_panel.add(search_by_cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 160, -1));

        jLabel10.setText("Busqueda por nombre");
        search_panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 20));

        search_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre del Libro", "Autor del Libro", "Categoria", "Editorial", "Año de publicacion", "Estado"
            }
        ));
        search_table.getTableHeader().setResizingAllowed(false);
        search_table.getTableHeader().setReorderingAllowed(false);
        search_table.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(search_table);

        search_panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 160, 480, 240));

        jLabel11.setText("Busqueda por Categoria");
        search_panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        jLabel12.setText("Busqueda por Autor");
        search_panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));
        search_panel.add(search_by_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 120, -1));

        search.setText("Buscar");
        search_panel.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));

        jTabbedPane1.addTab("Busqueda", search_panel);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("Editar", jPanel4);

        main_panel.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 510, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_bookActionPerformed
        // TODO add your handling code here:
        String nombre = add_name.getText();
        String autor = add_author.getText();
        String categoria = (String)add_cat.getSelectedItem();
        
    }//GEN-LAST:event_add_bookActionPerformed

    private void add_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_nameActionPerformed

    private void add_authorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_authorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_authorActionPerformed

    private void add_edActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_edActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_edActionPerformed

    private void add_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_yearActionPerformed

    private void search_by_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_by_catActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_by_catActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add_author;
    private javax.swing.JButton add_book;
    private javax.swing.JComboBox<String> add_cat;
    private javax.swing.JTextField add_ed;
    private javax.swing.JTextField add_name;
    private javax.swing.JPanel add_panel;
    private javax.swing.JTextField add_year;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel main_panel;
    private javax.swing.JLabel message;
    private javax.swing.JButton search;
    private javax.swing.JTextField search_by_author;
    private javax.swing.JComboBox<String> search_by_cat;
    private javax.swing.JTextField search_by_name;
    private javax.swing.JPanel search_panel;
    private javax.swing.JTable search_table;
    // End of variables declaration//GEN-END:variables
}
